# Generated by Django 3.2.5 on 2021-07-22 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(default=None)),
                ('last_name', models.TextField(default=None)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('password', models.IntegerField(default=None)),
                ('username', models.TextField(default=None)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default=None)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
            options={
                'db_table': 'Post',
            },
        ),
    ]
