# Generated by Django 3.2.5 on 2021-07-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None)),
                ('weight', models.IntegerField(default=None)),
                ('price', models.IntegerField(default=None)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
    ]
